# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09e538220f377e6ed286b383cbd46810"
name = "RojAi Agent"
application_url = "https://rojai-shopify.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[auth]
redirect_urls = [ "https://rojai-shopify.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
